-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 03:49:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imc01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imc01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imc01` DEFAULT CHARACTER SET utf8 ;
USE `imc01` ;

-- -----------------------------------------------------
-- Table `imc01`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imc01`.`usuarios` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `sexo` ENUM('M', 'F') CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `login` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `senha` INT(5) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `imc01`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imc01`.`registros` (
  `idregistro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarios_idusuario` INT UNSIGNED NOT NULL,
  `imc` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT '0.00',
  `datahora` VARCHAR(22) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idregistro`, `usuarios_idusuario`),
  INDEX `fk_registros_usuarios_idx` (`usuarios_idusuario` ASC),
  CONSTRAINT `fk_registros_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `imc01`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
